spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/visioDB?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
cloudinary:
  cloud-name: "${CLOUDINARY_NAME}"
  api-key: "${CLOUDINARY_NAME_API_KEY}"
  api-secret: "${CLOUDINARY_NAME_API_SECRET}"

  #  default.admin.pass: ${DEFAULT_ADMIN_PASS:root}

mail:
  host: sandbox.smtp.mailtrap.io
  port: 2525
  username: ${mailUsername}
  password: ${mailPassword}

dropbox:
  accessToken: "${DROPBOX-TOKEN}"


logging:
  level:
    #    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.org.jdbc.bind: TRACE
#    org.springframework.security: TRACE


