insert into visiodb.buildings (id, address, city, country, name, img_url)
values  (1, '45 Bd Raspail, 75006 Paris', 'Paris', 'France', 'Lutetia', null),
        (2, 'Gentsestraat 79, 8530 Harelbeke', 'Harelbeke', 'Belgium', 'Varbel', null),
        (3, 'София, ж.к. Младост 4, бул. Александър Малинов №78 ПК: 1799', 'Sofia', 'Bugaria', 'Softuni', null),
        (4, 'бул. „Пещерско шосе“ 80, 4002 Западна промишлена зона, Пловдив', 'Plovdiv', 'Bugaria', 'УСБАЛАГ "Селена"', null),
        (5, 'Отдих и Култура 1М, 4015 Западна промишлена зона, Пловдив', 'Plovdiv', 'Bugaria', 'Bugaria', null),
        (6, '4MPX+PX, 4001 Западна промишлена зона, Пловдив', 'Plovdiv', 'Bugaria', 'Западен парк резидънс 1 и 2', null),
        (7, 'Magnolia Residence, ул. „Рая“ 17, 4000 Западна промишлена зона, Пловдив', 'Plovdiv', 'Bugaria', 'Plovdiv', null),
        (8, '6, ул. „Лев Толстой“ str, 4017 Пловдив', 'Plovdiv', 'Bugaria', 'Hotel Imperial Plovdiv', null),
        (9, 'ул. „Братя Миладинови“, 8800 Сливен Център, Сливен', 'Sliven', 'Bugaria', '6, ул. „Лев Толстой“ str, 4017 Пловдив', null),
        (10, 'ул. „Предел“ 1, 8800 Сливен Център, Сливен', 'Sliven', 'Bugaria', 'Hotel Kredo', null),
        (11, 'бул. „Цар Освободител“ 6, 8800 Сливен Център, Сливен', 'Sliven', 'Bugaria', 'Hotel Хотел Парк Централ', null),
        (13, 'Mестност "Карандила, ж.к. Сини камъни, 8800 Сливен', 'Sliven', 'Bugaria', 'Комплекс "Сините камъни"', null),
        (14, 'ул. „Проф. д-р Иван Странски“ 20, 1000 ж.к. Малинова долина, София', 'Sofia', 'Bugaria', 'Кауфланд София-Малинова долина', null),
        (15, 'ул. „Владичина ливада“ 2, 1000 кв. Горубляне, София', 'Sofia', 'Bugaria', 'Кауфланд София Горубляне', null),
        (16, 'fdghfdgh', 'dfghfdgh', 'dfghfgh', 'fdghfdgh', 'test'),
        (17, 'dfghfdgh', 'dfghfdhg', 'dfghfdh', 'fghfgh', 'test'),
        (18, 'sfdsd', 'fsdffddf', 'fsd', 'sfadf', 'test'),
        (19, 'dfgsdfg', 'sdfgsdfg', 'sdfgsdfg', 'dsfgdsfg', 'http://res.cloudinary.com/daqpjk60x/image/upload/v1698837590/td2d23qsxsfagj6xv69c.png');
